export const PARAMETER_TYPE = {
  TRACE: 'TRACE',
  EVENT: 'EVENT',
  HEALTH: 'HEALTH',
}

export const PARAMETER_DATA_TYPE = {
  INTEGER: 'INTEGER',
  DOUBLE: 'DOUBLE',
  STRING: 'STRING',
  IMAGE: 'IMAGE',
  NUMERIC_TYPES: ['INTEGER', 'DOUBLE'],
  ALPHANUMERIC_TYPES: ['INTEGER', 'DOUBLE', 'STRING'],
}
